version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  nuxt:
    image: node:18
    container_name: nuxt_app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run dev"  # if you want to start this in production then replace this with npm run build and npm run start
    volumes:
      - .:/app 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
